"""empty message

Revision ID: 0331b682f8b4
Revises: c9e2bc0ed9b6
Create Date: 2022-06-12 00:05:47.127493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0331b682f8b4'
down_revision = 'c9e2bc0ed9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_book_voter_book_id_book'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_book_voter_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'book_id', name=op.f('pk_book_voter'))
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_categoryid_categories', type_='foreignkey')
        batch_op.drop_column('image')
        batch_op.drop_column('downloadcount')
        batch_op.drop_column('categoryid')
        batch_op.drop_column('title')
        batch_op.drop_column('authors')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('authors', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('categoryid', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('downloadcount', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key('fk_book_categoryid_categories', 'categories', ['categoryid'], ['id'], ondelete='CASCADE')

    op.drop_table('book_voter')
    # ### end Alembic commands ###
