"""empty message

Revision ID: 4351fd52e281
Revises: dafb43105864
Create Date: 2022-06-06 15:04:48.175654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4351fd52e281'
down_revision = 'dafb43105864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_book')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_categoryid_categories', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_book_categoryid_categories'), 'categories', ['categoryid'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bookshelf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('bookshlefid')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('categoryid')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_question_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoryid', sa.INTEGER(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('bookshelf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookshlefid', sa.INTEGER(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_book_categoryid_categories'), type_='foreignkey')
        batch_op.create_foreign_key('fk_book_categoryid_categories', 'categories', ['categoryid'], ['categoryid'], ondelete='CASCADE')

    op.create_table('_alembic_tmp_book',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('image', sa.TEXT(), nullable=True),
    sa.Column('categoryid', sa.INTEGER(), nullable=True),
    sa.Column('authors', sa.VARCHAR(length=200), nullable=False),
    sa.Column('downloadcount', sa.INTEGER(), nullable=True),
    sa.Column('grade', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['categoryid'], ['categories.id'], name='fk_book_categoryid_categories', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_book')
    )
    # ### end Alembic commands ###
