"""empty message

Revision ID: 5c7812eaf7ec
Revises: 
Create Date: 2022-05-26 19:49:40.541946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7812eaf7ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('categoryid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('categoryid', name=op.f('pk_categories'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('author', sa.String(length=8), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('audio', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('categoryid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoryid'], ['categories.categoryid'], name=op.f('fk_book_categoryid_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book'))
    )
    op.create_table('bookshelf',
    sa.Column('bookshlefid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('bookid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookid'], ['book.id'], name=op.f('fk_bookshelf_bookid_book'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], name=op.f('fk_bookshelf_userid_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bookshlefid', name=op.f('pk_bookshelf'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookshelf')
    op.drop_table('book')
    op.drop_table('user')
    op.drop_table('categories')
    # ### end Alembic commands ###
