"""empty message

Revision ID: 6dba05f23a93
Revises: f9d05c7085ad
Create Date: 2022-06-19 11:34:11.078473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dba05f23a93'
down_revision = 'f9d05c7085ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('authors')
        batch_op.drop_column('subjects')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subjects', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('authors', sa.VARCHAR(length=8), nullable=True))

    # ### end Alembic commands ###
