"""empty message

Revision ID: dafb43105864
Revises: 93c086976fe2
Create Date: 2022-06-06 14:58:40.455052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafb43105864'
down_revision = '93c086976fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_categoryid_categories', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_book_categoryid_categories'), 'categories', ['categoryid'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bookshelf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('bookshlefid')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('categoryid')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_question_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoryid', sa.INTEGER(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('bookshelf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookshlefid', sa.INTEGER(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_book_categoryid_categories'), type_='foreignkey')
        batch_op.create_foreign_key('fk_book_categoryid_categories', 'categories', ['categoryid'], ['categoryid'], ondelete='CASCADE')

    # ### end Alembic commands ###
