"""empty message

Revision ID: f9d05c7085ad
Revises: fa61de09ac5f
Create Date: 2022-06-17 16:24:35.472574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d05c7085ad'
down_revision = 'fa61de09ac5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subjects', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('authors', sa.String(length=8), nullable=True))
        batch_op.drop_column('author')
        batch_op.drop_column('audio')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('audio', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=8), nullable=True))
        batch_op.drop_column('authors')
        batch_op.drop_column('subjects')

    # ### end Alembic commands ###
