"""empty message

Revision ID: fa61de09ac5f
Revises: 3409bd2ee4d2
Create Date: 2022-06-13 17:16:59.224801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa61de09ac5f'
down_revision = '3409bd2ee4d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookid', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('bookid')

    # ### end Alembic commands ###
